"""Add connectors table

Revision ID: 138027b84c14
Revises: 5d65aec046c4
Create Date: 2025-03-27 11:41:04.907896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138027b84c14'
down_revision = '5d65aec046c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sample_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('collection_date', sa.DATE(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('location', sa.VARCHAR(length=50), nullable=False),
    sa.Column('volume', sa.VARCHAR(length=10), nullable=True),
    sa.Column('collection_time', sa.VARCHAR(length=10), nullable=True),
    sa.Column('processing_time', sa.VARCHAR(length=10), nullable=True),
    sa.Column('technician', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id')
    )
    # ### end Alembic commands ###
